services:
  # The server service now builds the entire application from the root Dockerfile
  server:
    build:
      context: . # Use the root directory as the build context
      dockerfile: Dockerfile
    container_name: eyangsmagicalteas-app # A more descriptive name
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
    networks:
      - app-network

# Networks
networks:
  app-network:
    driver: bridge